src/config/resolveConfig.js
src/util/execLive.js

This looks a lot better, since it makes it so you can see installation progress,
rather than getting it all at the end.

fix: forward stdout when installing binaries

---

README.md
src/check.js
src/convert.js
test/test.js

This is the preferred way of writing it, I believe, so use a lower-case 'd' in
author names, commit messages, and other messages.

fix: always write "decaffeinate" in lower-case

---

src/config/resolveConfig.js

It still isn't great, but it says the file that's wrong and the fact that it was
invalid JSON.

fix: improve error handling when a config file is invalid json

---

README.md
package.json
src/cli.js
src/config/resolveConfig.js
src/convert.js
test/examples/jscodeshift-test/A.coffee
test/examples/jscodeshift-test/bulk-decaffeinate.json
test/examples/jscodeshift-test/change-name.js
test/test.js

A new config setting lets you specify an array of script paths to run once
decaffeinate finishes. Like with decaffeinate and eslint, we prompt to install
jscodeshift if necessary, but we only do this if any paths are actually
specified.

feat: optionally run jscodeshift scripts after decaffeinate

---

README.md

One point has already been done, one seems lower priority, and one is more
vague, so it seems reasonable to just get rid of it.

docs: remove the "future plans" section from the README

---

src/convert.js
test/test.js

This avoids the issue where changes could get lumped in with the decaffeinate
changes inadvertently.

fix: fail if there are uncommitted git changes when running convert

---

README.md
src/clean.js
src/cli.js
src/config/getCoffeeFilesUnderPath.js
src/util/getFilesUnderPath.js
test/test.js

These backups are usually harmless, but they can cause problems if they get
auto-discovered by the test runner, and it's annoying to have them around once
the conversion is complete. Programmatically deleting files is scary, so I made
the help text make it very clear what it does.

feat: add a "clean" command that deletes .original.coffee files

---

jscodeshift-scripts/fix-imports.js
test/examples/fix-imports-no-name-usages/DirectModuleUsage.coffee
test/examples/fix-imports-no-name-usages/DirectModuleUsage.js.expected
test/examples/fix-imports-no-name-usages/NamedExports.js
test/examples/fix-imports-no-name-usages/bulk-decaffeinate.json
test/test.js

In some cases, a name could be imported and only used by itself (e.g. passed
into a mocking function). If the other side had a default export, then this
would be fine, but if the other side had no default export, we would just leave
off any type of import name. Now, we instead switch the import to an `import *`
in that case.

fix: keep imports even when no fields are used

---

src/convert.js
test/test.js

jscodeshift discovers and converts and files importing a file that was run
through decaffeinate, so we don't have a nice list of files to `git add`. But we
already made sure at the start that the git worktree has no changes, so it
should be safe to just add all files.

fix: add all files after running fix-imports, not just decaffeinated files

---

jscodeshift-scripts/fix-imports.js

It looks like the babel config was set up right when I was testing locally, but
not when running from a real package, so there would be an "unexpected token"
error. The easy (though ironic) fix is to just use commonjs style for the script
itself.

fix: avoid crash in fix-imports by switching to commonjs

---

jscodeshift-scripts/fix-imports.js
test/examples/fix-imports-non-relative-path/NonRelativePath.coffee
test/examples/fix-imports-non-relative-path/NonRelativePath.js.expected
test/examples/fix-imports-non-relative-path/bulk-decaffeinate.config.js
test/test.js

This fixes an issue where an import like 'foo' would look for 'foo.js' in the
current directory and have that take precedence over global or node_modules
matches, which is wrong. Now, we see if the first letter is '.' to know if the
import is relative or absolute.

fix: properly detect relative vs non-relative imports in fix-imports

---

.gitignore
jscodeshift-scripts/fix-imports.js
package.json
src/convert.js

The fix-imports script worked when run from source (using `npm link`), but not
when bulk-decaffeinate was installed as a package. The issue is that
jscodeshift wasn't properly running babel (I think because the file was within
node_modules), so the simple fix is to just run babel myself and ship the
compiled version.

fix: run the fix-imports script through babel as part of the build process

---

README.md
src/cli.js
src/config/resolveConfig.js
test/test.js

This makes it easier to convert just one or two files, and makes some tests
easier to write.

feat: allow specifying files from the command line

---

src/convert.js
test/test.js

Instead of just saying the number of files that were converted, we now say the
name of the first file and the number of other files. There's more smart stuff
that could be done like finding a common directory among the files or using the
args that were passed in originally, but I'll leave that until later.

fix: show nicer-looking commit messages

---

README.md
jscodeshift-scripts/prefer-function-declarations.js
src/convert.js
test/examples/builtin-jscodeshift-script/Func.coffee
test/examples/builtin-jscodeshift-script/bulk-decaffeinate.config.js
test/test.js

This is optional, but useful for fixing some eslint issues. This commit also
adds a general mechanism for including built-in jscodeshift scripts, which may
be useful later.

feat: add a jscodeshift script to prefer function declarations

---

jscodeshift-scripts/prefer-function-declarations.js
test/examples/builtin-jscodeshift-script/Func.coffee
test/test.js

We need to transfer comments from all nodes that aren't kept in the new AST.

fix: don't drop comments in prefer-function-declarations.js

---

.travis.yml
package.json
src/convert.js
src/util/gitTrackedStatus.js
src/util/makeCommit.js
test/test.js

Also move away from some shell commands in favor of more native move, copy, and
delete functions.
The tests still use shell commands, and could maybe be moved over in the future.

refactor: use nodegit in the convert command

---

README.md
src/cli.js
src/config/getCoffeeFilesFromPathFile.js
src/config/resolveConfig.js
src/land.js

This is especially useful for Phabricator workflows where you ideally want to
update every commit message to point to the code review. But it's also useful in
general for making it a little easier to push a change that includes independent
commits.
Unfortunately, tests for this command are hard because it runs `fetch` and
`arc`, so I'll punt on tests for now.

feat: add a "land" command

---

src/convert.js
src/util/CLIError.js

This is a bit faster than doing a full JS parse on each file, and is also nice
in that it lets us know which files we need to add in git.
This also fixes a race condition where the nodegit "status" command wasn't
returning all files that should be committed.

fix: pre-process JS files to determine which are eligible for fix-imports

---

src/config/resolveConfig.js

We already ignored one validity check, but not another. This should make it
possible to run "land" with JS files already existing for the configuration.

fix: properly ignore file validity check for "land" command

---

jscodeshift-scripts/fix-imports.js
src/convert.js

On Mac, there's a default system limit of 256K for any shell commands. When we
invoke jscodeshift, we explicitly specify every path to transform and we also
include a base64ed JSON string with that same array of absolute paths. When
running bulk-decaffeinate on my entire codebase, this was generating a command
of length about 280K, so it was crashing.
To address this, I reduced the size in two ways:
* I use relative instead of absolute paths for the list of files sent to
jscodeshift. This reduced the length of that part by about a factor of 2 for
me.
* I gzip-compress the JSON string and decompress on the other end. This reduced
the length of that part by about a factor of 10.
Overall this reduced the arg size by a factor of about 2.5, down to 100K.

fix: reduce the size of the jscodeshift command for fix-imports

---

src/runner/runWithProgressBar.js

On my 4-core laptop, this reduced the time to run `check` on my codebase from
about 15 minutes to about 10 minutes.

fix: increase the parallelism from 4 to 8

---

README.md
package.json
src/check.js
src/config/resolveConfig.js
src/convert.js
test/examples/decaffeinate-args-test/A.coffee
test/examples/decaffeinate-args-test/bulk-decaffeinate.config.js
test/test.js

Unfortunately, invalid args fail pretty poorly at the moment, but I think that
can be fixed on the decaffeinate side.
Also clean up some test code to better assert success.

feat: add a config option for specifying decaffeinate args

---

jscodeshift-scripts/fix-imports.js
test/examples/fix-imports-import-commonjs/ImportThree.coffee
test/examples/fix-imports-import-commonjs/ImportThree.js.expected
test/examples/fix-imports-import-commonjs/bulk-decaffeinate.config.js
test/examples/fix-imports-import-commonjs/three.js
test/test.js

When an import statement point at a file without any exports at all (e.g. a
commonjs module), the fix-imports script was viewing it as a file with only
named exports (which is vacuously true) and changing the import style to
`import *`. This broke cases where a commonjs module exported anything other
than an object.

fix: don't modify imports when they point at a module with no exports

---

src/runner/makeCLIFn.js

Some decaffeinate runs had more than 200KB of stdout, which gave an error
message.

fix: increase buffer size to 5MB when running CLI commands

---

jscodeshift-scripts/prefer-function-declarations.js
test/examples/builtin-jscodeshift-script/Func.coffee
test/test.js

The esnext stage can turn some functions into arrow functions. This transform misses those. To make it safer, arrow functions will only be transformed if it is part of a top-level variable declaration.

feat: prefer function declarations for arrow functions too

---

jscodeshift-scripts/prefer-function-declarations.js
test/examples/builtin-jscodeshift-script/Func.coffee
test/test.js

Previously it would change an arrow function returning 5 into this code:
```js
function arrowWithComment() {
return // This is a comment
5;
}
```
which has a semicolon inserted after the `return`. This looks like a bug in
jscodeshift/recast, but the quick fix is to reposition any comments onto the
return statement rather than the returned expression.

fix: work around jscodeshift bug when converting arrow functions with comments

---

package.json

Hopefully this should fix things so semantic-release generates a GitHub release
in the newly-moved repo.

fix: update package.json URLs for GitHub repository

---

README.md
src/cli.js
src/config/resolveConfig.js
test/examples/invalid-subclass-constructor/A.coffee
test/test.js

This is useful to check a repo for decaffeinate problems without needing a
config file.

feat: add an --allow-invalid-constructors option

---

package.json
src/convert.js
src/util/gitTrackedStatus.js
src/util/isWorktreeEmpty.js

Progress toward #86
Progress toward #98
First step in moving off of nodegit, mostly taken from @refack's branch from #86.

fix: add simple-git dependency, use it when checking for tracked files

---

src/cli.js
test/test.js

An eslint parsing error was causing strange results when converting the atom
project, partially caused by the script not failing when bulk-decaffeinate
failed. This should make it easier to spot errors earlier.

fix: exit 1 when there is an exception

---

src/check.js
src/convert.js
src/runner/runWithProgressBar.js

Previously, it would just continue.

fix: exit 1 when there is a failure at any step under a progress bar

---

src/convert.js

Previously, it would always parse the result as JSON, but if it was an error
message, it would just be invalid JSON.

fix: display the full error when eslint fails

---

src/convert.js

In some cases, projects may have .js files in gitignore. Anything generated by
bulk-decaffeinate is something we're pretty confident we want to commit, so it
seems reasonable to pass `-f` to `git add`.

fix: force-add files when committing

---

src/check.js
src/cli.js
src/config/getCoffeeFilesFromPathFile.js
src/config/getFilesToProcess.js
src/config/resolveConfig.js
src/convert.js
test/bulk-decaffeinate-test.js
test/convert-test.js
test/examples/file-list/files-to-decaffeinate.txt

Previously, it happened at config resolution time, which was awkward because
some commands didn't care about the list of files.
This also sets us up to make the set of files more flexible.

refactor: change file validation to happen explicitly

---

README.md
src/config/getFilesToProcess.js
src/config/resolveConfig.js
test/bulk-decaffeinate-test.js
test/convert-test.js
test/examples/multiple-path-specifiers/A.coffee
test/examples/multiple-path-specifiers/B.coffee
test/examples/multiple-path-specifiers/C.coffee
test/examples/multiple-path-specifiers/D.coffee
test/examples/multiple-path-specifiers/bulk-decaffeinate.config.js
test/examples/multiple-path-specifiers/dir1/E.coffee
test/examples/multiple-path-specifiers/dir1/F.coffee
test/examples/multiple-path-specifiers/dir2/G.coffee
test/examples/multiple-path-specifiers/dir2/H.coffee
test/examples/multiple-path-specifiers/paths.txt
test/test-util.js

This makes it possible to do an automatic search and also opt-in specific files
(like `Cakefile`).
BREAKING CHANGE: Rather than defining precedence rules for different path config
options, we now allow multiple options and union the results.
BREAKING CHANGE: Config files ending in .json are no longer supported. Config
files must be JS files ending in .config.js.

feat: change file resolution algorithm to union all specifiers

---

src/util/getFilesUnderPath.js
test/bulk-decaffeinate-test.js
test/convert-test.js
test/examples/executable-extensionless-scripts/bin/nestedExecutableScript

Previously, if there was a nested extensionless script, bulk-decaffeinate would
crash because it would only use the filename, not the full path.

fix: provide proper paths when checking if scripts are executable

---

README.md
src/clean.js
test/convert-test.js
test/examples/backup-files/A.coffee
test/examples/backup-files/B.coffee.md
test/examples/backup-files/C
test/test-util.js

This is a little unsafe in that it's more likely to get false positives, but
should still be safe since people should be running this within a git repo and
because it skips node_modules.

fix: change "clean" to remove all types of .original files

---

src/config/getFilesToProcess.js
src/convert.js
src/util/FilePaths.js
src/util/getFilesUnderPath.js
src/util/getTrackedFiles.js
src/util/isWorktreeEmpty.js
test/bulk-decaffeinate-test.js
test/convert-test.js
test/fix-imports-test.js
test/test-util.js

Fixes #98
Fixes #120
Untracked files no longer block bulk-decaffeinate from running. But they do show
a warning since it might indicate a mistake.
Similarly, when discovering files, we skip any untracked files that would
otherwise be converted, and we show a warning in that case (hopefully untracked
CoffeeScript files are rare anyway).
If an untracked files are explicitly specified for conversion, we now fail with
a friendlier error than before.

feat: rework handling of untracked files

---

src/convert.js

This avoids a crash due to the shell command being too long, and should
hopefully avoid the new error in the codecombat example project.

fix: convert paths to relative when invoking jscodeshift

---

README.md
src/config/resolveConfig.js
test/bulk-decaffeinate-test.js
test/examples/search-directory-config/A.coffee
test/examples/search-directory-config/B.coffee
test/examples/search-directory-config/bulk-decaffeinate.config.js

This fixes an annoyance that was also causing trouble in the
decaffeinate-examples project. When specifying a path file, like the successful
files after `check`, it should only convert those files, not union them with the
existing config.

feat: when specifying files from the CLI, ignore the equivalent config settings

---

README.md
package.json
src/cli.js
src/config/resolveConfig.js
test/convert-test.js
test/examples/fix-imports-absolute-imports/bulk-decaffeinate.config.js
test/examples/fix-imports-default-import-to-import-star/bulk-decaffeinate.config.js
test/examples/fix-imports-destructure-from-import-star/bulk-decaffeinate.config.js
test/examples/fix-imports-export-function/bulk-decaffeinate.config.js
test/examples/fix-imports-import-commonjs/bulk-decaffeinate.config.js
test/examples/fix-imports-import-from-existing-js/bulk-decaffeinate.config.js
test/examples/fix-imports-named-import-to-destructure/NamedImport.js.expected
test/examples/fix-imports-named-import-to-destructure/bulk-decaffeinate.config.js
test/examples/fix-imports-no-name-usages/bulk-decaffeinate.config.js
test/examples/fix-imports-non-relative-path/bulk-decaffeinate.config.js
test/examples/fix-imports-star-import-from-existing-js/bulk-decaffeinate.config.js
test/examples/invalid-subclass-constructor/A.coffee
test/fix-imports-test.js
test/modernize-js-test.js

* Add a `--use-js-modules` option that performs the fix-imports step and sets
the decaffeinate args to use JS modules.
* Update a bunch of tests to reflect the defaults changes.
* Make the `--allow-invalid-constructors` option a no-op, since it isn't needed
with decaffeinate 3.0.
* Update the README example to no longer use `--allow-invalid-constructors`.
Also change it from hubot to coffeelint, since hubot is now a JS project.
BREAKING CHANGE: The `--allow-invalid-constructors` option is now a no-op.

feat: update bulk-decaffeinate for decaffeinate 3.0

---

package.json
src/runner/runWithProgressBar.js

This should make it easier to diagnose performance issues from logs.

feat: add timing information after every progress bar step

---

package.json
src/modernize/runEslintFix.js

Fixes #134
Newer eslint puts the message on stderr, and older eslint puts it on stdout, so
just check both.

fix: properly detect missing eslint config file for newer eslint

---

README.md
src/cli.js
src/config/resolveConfig.js
src/convert.js
src/modernizeJS.js
test/convert-test.js
test/examples/skip-eslint-fix/A.coffee
test/examples/skip-eslint-fix/bulk-decaffeinate.config.js

This is useful if you're not using eslint for whatever reason or to reduce the
total running time.
This also changes the requirements code to be a little smarter and not prompt to
install things that we don't need for the current operation.

feat: add an option to skip the eslint step

---

package.json
src/runner/runWithProgressBar.js
src/util/momentPreciseDiff.js

Fixes #140
This change just inlines the code into this package, since the way that the
plugin installed itself on the moment package was fragile.

fix: drop moment-precise-range-plugin dependency

---

README.md

This PR fixes the badge link and image to point to the current Travis project.
This turns the badge 💚 green 💚, since the _build is working._

README: Update the Travis badge to "decaffeinate"

---

.travis.yml
jscodeshift-scripts/fix-imports.js

This should fix the build. I won't call it a breaking change since it doesn't
cause any breaking changes in the package. Node 4 hasn't been supported in
quite a while anyway, so I won't bother looking into the specific failure.
Also update a usage of Buffer to fix a warning in node 10.

fix: update node versions run on Travis
